cabal-version: 3.14

name: boh
version: 0.0.0.0

common common
  build-depends:
    , base >= 4.21.0 && < 4.22
  default-extensions:
    NoImplicitPrelude
  default-language:
    Haskell2010
  ghc-options:
    -Wall

library
  import:
    , common
  hs-source-dirs:
    src
  exposed-modules:
    Boh
    Boh.Applicative
    Boh.Functor
    Boh.List
    Boh.Monad
    Boh.Monoid
    Boh.Prelude
    Boh.Semigroup
  build-depends:
    , markdown-unlit >= 0.6.0 && < 0.7
  build-tool-depends:
    markdown-unlit:markdown-unlit
  ghc-options:
    -pgmL markdown-unlit
  default-extensions:
    InstanceSigs

source-repository head
  type: git
  location: https://github.com/jpvillaisaza/boh
